#!/usr/bin/env bash
# generate_role_mappings.sh
# Automatically generates the role_id_map substitution file from all YAML configs
# Scans all *.yaml files, extracts "role:" substitution, and generates MD5-based role_ids
# This ensures the role_id_map is always complete and up-to-date

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROLE_MAPPINGS_FILE="$SCRIPT_DIR/substitutions/role_ids.yaml"
ROLE_IDS_DIR="$SCRIPT_DIR/substitutions"

# Create substitutions directory if it doesn't exist
mkdir -p "$ROLE_IDS_DIR"

# Extract all roles from YAML files and generate mapping
python3 << 'PYEOF'
import os
import re
import hashlib
import yaml

script_dir = os.environ.get('SCRIPT_DIR', '.')
role_mappings_file = os.environ.get('ROLE_MAPPINGS_FILE', os.path.join(script_dir, 'substitutions/role_ids.yaml'))

roles = {}

# Find all YAML files (excluding substitutions directory itself)
for root, dirs, files in os.walk(script_dir):
    # Skip substitutions directory and hidden directories
    dirs[:] = [d for d in dirs if not d.startswith('.') and d != 'substitutions']

    for file in files:
        if not file.endswith('.yaml'):
            continue

        filepath = os.path.join(root, file)

        try:
            with open(filepath, 'r') as f:
                content = f.read()

            # Add custom constructor for !secret tag (used in ESPHome YAML)
            def secret_constructor(loader, node):
                return f"!secret {node.value}"
            yaml.add_constructor('!secret', secret_constructor, Loader=yaml.SafeLoader)

            data = yaml.safe_load(content)

            # Extract role from substitutions block only
            if data and isinstance(data, dict):
                substitutions = data.get('substitutions', {})
                if isinstance(substitutions, dict) and 'role' in substitutions:
                    role_name = substitutions['role']
                    if isinstance(role_name, str):
                        # Generate deterministic role_id from role name using MD5
                        role_id = hashlib.md5(role_name.encode()).hexdigest()[:18]
                        roles[role_name] = role_id
                        print(f"Found role: {role_name:30} → {role_id}")
        except Exception as e:
            print(f"Warning: Could not process {filepath}: {e}", file=__import__('sys').stderr)

if not roles:
    print("Warning: No roles found in YAML files", file=__import__('sys').stderr)
    exit(1)

# Generate YAML content for role_id_map
yaml_content = """# Auto-generated role ID mapping
# DO NOT EDIT MANUALLY - generated by generate_role_mappings.sh
#
# This file maps ESPHome device roles to stable 18-character IDs computed from:
#   role_id = md5(role_name)[:18]
#
# When you add a new YAML device config with a 'role' substitution,
# run: ./generate_role_mappings.sh
# This will auto-detect your new role and add it to the mapping below.

substitutions:
  role_id_map:
"""

# Add roles sorted alphabetically
for role_name in sorted(roles.keys()):
    role_id = roles[role_name]
    yaml_content += f"    {role_name}: \"{role_id}\"  # md5(\"{role_name}\")[:18]\n"

# Write the mapping file
with open(role_mappings_file, 'w') as f:
    f.write(yaml_content)

print(f"\n✓ Generated role_id_map with {len(roles)} role(s)")
print(f"✓ Written to: {role_mappings_file}")

PYEOF
