#!/bin/bash
# REFERENCE ONLY: Partition table configuration
#
# NOTE: This file is NOT used at runtime. Partition sizes are calculated dynamically
# by iotstack.sh AFTER firmware compilation based on actual firmware.bin size.
#
# This file documents the fixed partition boundaries and sizing strategy.
# Do NOT edit this file to change partition sizes - changes won't take effect.
#
# Partition Layout:
# - Bootloader: 0x0-0x8000 (32KB, fixed)
# - NVS: 0x9000-0xd000 (16KB, fixed)
# - OTA Data: 0xd000-0xf000 (8KB, fixed)
# - Recovery: 0x30000-??? (sized to firmware + margin)
# - Production: ???-??? (same size as recovery, offset calculated)
#
# Calculation happens in _calculate_partition_sizes() after each compilation.

# Fixed boundaries
FLASH_SIZE=0x400000      # 4MB total
BOOTLOADER_OFFSET=0x0
BOOTLOADER_SIZE=0x8000
NVS_OFFSET=0x9000
NVS_SIZE=0x4000          # 16KB fixed
OTADATA_OFFSET=0xd000
OTADATA_SIZE=0x2000      # 8KB fixed
RECOVERY_OFFSET=0x30000  # Offsets calculated after compilation

# Example defaults (overridden at runtime by _calculate_partition_sizes):
RECOVERY_SIZE=0x180000    # Example: 1.5MB (actual calculated from firmware)
PRODUCTION_SIZE=0x240000  # Example: 2.25MB (matches recovery size)
PRODUCTION_OFFSET=0x1b0000 # Example offset (actual calculated)
