#!/bin/bash
# Generate partition table based on actual firmware sizes
# Recovery partition gets exactly what it needs + 5% buffer
# Production partition gets all remaining space
#
# Usage:
#   ./scripts/generate-partitions.sh recovery.bin production.bin [--output partitions/iotstack_partition_table.csv]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Parse arguments
RECOVERY_BIN="${1:-}"
PRODUCTION_BIN="${2:-}"
OUTPUT_FILE="${3:---output}"
OUTPUT_PATH="${4:-$PROJECT_DIR/partitions/iotstack_partition_table.csv}"

# Handle --output flag
if [[ "$OUTPUT_FILE" != "--output" ]]; then
  OUTPUT_PATH="$OUTPUT_FILE"
fi

# Validate arguments
if [[ -z "$RECOVERY_BIN" ]] || [[ -z "$PRODUCTION_BIN" ]]; then
  cat >&2 << 'EOF'
Usage: generate-partitions.sh <recovery.bin> <production.bin> [--output <path>]

Examples:
  # Generate partition table from compiled binaries
  ./scripts/generate-partitions.sh \
    .iotstack/.esphome/build/recovery/build/recovery.bin \
    .iotstack/.esphome/build/bleproxy/build/bleproxy.bin

  # Save to custom path
  ./scripts/generate-partitions.sh \
    recovery.bin production.bin \
    --output partitions/custom.csv

EOF
  exit 1
fi

# Check files exist
if [[ ! -f "$RECOVERY_BIN" ]]; then
  echo "[ERR] Recovery binary not found: $RECOVERY_BIN" >&2
  exit 1
fi

if [[ ! -f "$PRODUCTION_BIN" ]]; then
  echo "[ERR] Production binary not found: $PRODUCTION_BIN" >&2
  exit 1
fi

# Get actual file sizes in bytes
RECOVERY_SIZE=$(stat -f%z "$RECOVERY_BIN" 2>/dev/null || stat -c%s "$RECOVERY_BIN")
PRODUCTION_SIZE=$(stat -f%z "$PRODUCTION_BIN" 2>/dev/null || stat -c%s "$PRODUCTION_BIN")

echo "[INFO] Firmware sizes:"
echo "  Recovery:  $((RECOVERY_SIZE / 1024))KB"
echo "  Production: $((PRODUCTION_SIZE / 1024))KB"

# Add 5% safety buffer to recovery (buffer = size / 20)
RECOVERY_BUFFER=$(( (RECOVERY_SIZE * 5) / 100 ))
RECOVERY_PARTITION_SIZE=$(( RECOVERY_SIZE + RECOVERY_BUFFER ))

# Round up to nearest 64KB boundary (ESPHome/ESP-IDF requirement)
# Formula: ((size + 65535) / 65536) * 65536
RECOVERY_PARTITION_SIZE=$(( ((RECOVERY_PARTITION_SIZE + 65535) / 65536) * 65536 ))

# Production gets remaining space in 4MB flash
# Layout: 0x0000-0x20000 (bootloader), 0x20000-0x24000 (partition table), 0x24000+ (apps)
FLASH_SIZE=$((4 * 1024 * 1024))  # 4MB = 4194304 bytes
RECOVERY_START=$((0x24000))       # 147456
PRODUCTION_START=$((RECOVERY_START + RECOVERY_PARTITION_SIZE))

# Production partition size = everything from PRODUCTION_START to end of flash
PRODUCTION_PARTITION_SIZE=$((FLASH_SIZE - PRODUCTION_START))

echo ""
echo "[INFO] Partition allocation:"
echo "  Recovery offset:  0x$(printf '%x' $RECOVERY_START) ($((RECOVERY_START / 1024))KB)"
echo "  Recovery size:    0x$(printf '%x' $RECOVERY_PARTITION_SIZE) ($((RECOVERY_PARTITION_SIZE / 1024))KB)"
echo "  Production offset: 0x$(printf '%x' $PRODUCTION_START) ($((PRODUCTION_START / 1024))KB)"
echo "  Production size:  0x$(printf '%x' $PRODUCTION_PARTITION_SIZE) ($((PRODUCTION_PARTITION_SIZE / 1024))KB)"

# Verify we fit in 4MB
TOTAL_APP_SIZE=$((RECOVERY_PARTITION_SIZE + PRODUCTION_PARTITION_SIZE))
if [[ $((RECOVERY_START + TOTAL_APP_SIZE)) -gt $FLASH_SIZE ]]; then
  echo "[ERR] Total app partition size exceeds 4MB flash!" >&2
  echo "  Recovery + Production = $((TOTAL_APP_SIZE / 1024))KB (max available: ~3.8MB)" >&2
  exit 1
fi

# Create output directory if needed
mkdir -p "$(dirname "$OUTPUT_PATH")"

# Generate partition table
cat > "$OUTPUT_PATH" << EOF
# ESP32-C6 Partition Table for Dual App OTA Recovery
# Auto-generated by scripts/generate-partitions.sh
# Recovery: $((RECOVERY_SIZE / 1024))KB + 5% buffer = $((RECOVERY_PARTITION_SIZE / 1024))KB
# Production: $((PRODUCTION_SIZE / 1024))KB allocated $((PRODUCTION_PARTITION_SIZE / 1024))KB
#
# Name,     Type,  SubType,    Offset,     Size,      Flags
nvs,        data,  nvs,        0x9000,     0x4000,
otadata,    data,  ota,        0xd000,     0x2000,
recovery,   app,   ota_0,      0x$(printf '%x' $RECOVERY_START),  0x$(printf '%x' $RECOVERY_PARTITION_SIZE),
production, app,   ota_1,      0x$(printf '%x' $PRODUCTION_START),  0x$(printf '%x' $PRODUCTION_PARTITION_SIZE),
EOF

echo ""
echo "[OK] Partition table generated: $OUTPUT_PATH"
echo ""
echo "[INFO] Use in YAML:"
echo "  esp32:"
echo "    partitions: custom:partitions/iotstack_partition_table.csv"
