#!/bin/bash
# partition-table.sh — Generate and manage the iotstack partition table artifact
#
# Requires config.sh to be sourced first (PARTITION_TABLE, PARTITION_TABLE_SYMLINK,
# IOTSTACK_* layout variables).

generate_partition_table() {
  # Emit the fixed 2-partition table to stdout.
  #
  # Layout (permanent):
  #   ota_0 = failsafe   (fixed size: IOTSTACK_FAILSAFE_PART_SIZE)
  #   ota_1 = production (absorbs all remaining flash)
  local flash_size="${IOTSTACK_FLASH_SIZE:-0x400000}"
  local app_offset="${IOTSTACK_APP_OFFSET:-0x30000}"
  local failsafe_size="${IOTSTACK_FAILSAFE_PART_SIZE:-0x100000}"

  # Production starts right after failsafe, 64KB-aligned (ESP32 app alignment).
  local prod_offset=$(( app_offset + failsafe_size ))
  if (( prod_offset % 0x10000 != 0 )); then
    prod_offset=$(( (prod_offset / 0x10000 + 1) * 0x10000 ))
  fi
  local prod_size=$(( flash_size - prod_offset ))
  if (( prod_size <= 0 )); then
    echo "Failsafe partition ($failsafe_size) leaves no room for production in $flash_size flash" >&2
    return 1
  fi

  printf '# ESP32-C6 2-partition table: permanent failsafe (ota_0) + production (ota_1)\n'
  printf '# All OTA updates run from failsafe, so production (ota_1) is always the OTA\n'
  printf '# target and failsafe (ota_0) is never overwritten. Generated by iotstack.\n'
  printf '# Name,     Type, SubType, Offset,    Size,\n'
  printf 'nvs,        data, nvs,     0x9000,    0x4000,\n'
  printf 'otadata,    data, ota,     0xd000,    0x2000,\n'
  printf 'failsafe,   app,  ota_0,   %s, %s,\n' "$app_offset" "$failsafe_size"
  printf 'production, app,  ota_1,   0x%x, 0x%x,\n' "$prod_offset" "$prod_size"
}

_ensure_partition_table_symlink() {
  local output_file="$1"
  local symlink_path="${PARTITION_TABLE_SYMLINK}"

  if [[ ! -L "$symlink_path" ]] || [[ "$(readlink "$symlink_path")" != "$output_file" ]]; then
    rm -f "$symlink_path"
    ln -s "$output_file" "$symlink_path"
  fi
}

_migrate_legacy_partition_table() {
  # Older releases stored the table directly under ~/.iotstack/.
  local legacy="${IOTSTACK_HOME}/${PARTITION_TABLE_CSV}"
  if [[ -f "$legacy" && "$legacy" != "$PARTITION_TABLE" && ! -f "$PARTITION_TABLE" ]]; then
    mv "$legacy" "$PARTITION_TABLE"
  fi
}

ensure_partition_table_artifact() {
  # Create a stub partition table and yamls/ symlink if missing. Idempotent.
  mkdir -p "$(dirname "$PARTITION_TABLE")"
  _migrate_legacy_partition_table
  if [[ ! -f "$PARTITION_TABLE" ]]; then
    generate_partition_table > "$PARTITION_TABLE"
  fi
  _ensure_partition_table_symlink "$PARTITION_TABLE"
}

update_partition_table_file() {
  # Regenerate the partition table from current IOTSTACK_* variables.
  mkdir -p "$(dirname "$PARTITION_TABLE")"
  generate_partition_table > "$PARTITION_TABLE"
  _ensure_partition_table_symlink "$PARTITION_TABLE"
}